### ISSUE TITLE
this.setState with asynchronous problem

### ISSUE THREAD

**Issue by taweesoft** [gregchamberlain/react-chips#1]
in addChips(..) 
you call `this.props.onChange(this.state.chips)` after this.setState(..)
but the new state is not send to onChange because of asynchronous.
So you have to call this.props.onChange with `chips`  variable because it is the new state.

**Comment by gregchamberlain** [comment]
You are absolutely correct, fixed now. Thanks!

**Comment by taweesoft** [comment]
onBackSpace() too man

**Comment by gregchamberlain** [comment]
Got it, Thanks. I'll probably end up changing this into a controlled input and not hold this chips in state. Originally made this component when I first learned react so the code is a bit sloppy. Let me know if you notice anything else.
