### ISSUE TITLE
Possibility to Return event onChange

### ISSUE THREAD

**Issue by yanv1991** [gregchamberlain/react-chips#14]
Maybe I didn't see any solution in the docs but, when I have multiple chips instances in a same class component for example its very difficult to identify which one was updated to pass on setState so probably we can have access to the event object to get name of the current chip

**Comment by gregchamberlain** [comment]
If I'm understanding your problem correctly, an easy solution would be to return your onChange handler from another function and close over a value of the instance of `Chips` that calls it. Heres an example.

```js
class YourComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      chips1: [],
      chips2: []
    }
  }

  handleOnChange = (chipKey) => (value) => {
    this.setState({ [chipKey]: value });
  }

  render() {
    return (
      <div>
        <Chips value={this.state.chips1} onChange={handleOnChange('chips1')} />
        <Chips value={this.state.chips2} onChange={handleOnChange('chips2')}>
      </div>
    )
  }
}
```

Let me know if that works for you.

**Comment by yanv1991** [comment]
Yes that solved my problem, with the higher order function, thank you
