### ISSUE TITLE
How to style

### ISSUE THREAD

**Issue by lucasbento** [gregchamberlain/react-chips#18]
I don't get how we are supposed to style it, I'm trying to use it with [material-ui v1](https://github.com/callemall/material-ui/tree/v1-beta) and make it look like material design, would you be able to provide a small example of how to style it?

Thank you!

**Comment by gregchamberlain** [comment]
Right now the styling works using [react-themeable](https://github.com/markdalgleish/react-themeable) (see their docs for all the options for what a theme object can be). 

The `chipsContainer` key will style the container that holds the chips. The theme is also passed down to [react-autosuggest](https://github.com/moroshko/react-autosuggest#theme-optional) (the underlying component for autocomplete), so you can use the keys in their docs to style the input and autocomplete list. The default theme can be found [here](https://github.com/gregchamberlain/react-chips/blob/master/src/theme.js).

For styling each chip, you can use a [custom chip component](https://github.com/gregchamberlain/react-chips#custom-chip-component) in the `renderChip` prop. Theres an example [here](https://github.com/gregchamberlain/react-chips/blob/master/stories/index.js#L57). The custom chip gets passed a selected and onRemove prop so you can add additional styling if the chip is selected, and request to remove the chip from the custom chip component.

I'm planning on revamping this package to make it more customizable sometime in the future (which will probably move away from using react-themable). I don't have a timeline for that though, mostly depends on my schedule. 

Let me know if you need anymore pointers, thanks!

**Comment by lucasbento** [comment]
Got it working, thank you so much, @gregchamberlain!
