### ISSUE TITLE
Make the key to create a chip customizable.

### ISSUE THREAD

**Issue by jaeg** [gregchamberlain/react-chips#2]
It took looking at the code to realize creating a non-suggested chip requires hitting the tab key.  Would it be possible to have this be customizable from the html tag level?

**Comment by gregchamberlain** [comment]
Yeah, that would be pretty simple to implement and something I've thought about adding before but haven't gotten around to it. I could add another prop that takes an array of keys/keyCodes to create a chip. I'll try to get around to it this weekend!

**Comment by jaeg** [comment]
That would be awesome!  Thanks!  :)

**Comment by gregchamberlain** [comment]
I added a createChipKeys prop that can be passed an array of keys/keyCodes to be used to create a new chips (see new docs). Just have to upgrade to version 0.4.0 to use it.
