### ISSUE TITLE
FromSugesstionsOnly

### ISSUE THREAD

**Issue by pratik-sinha** [gregchamberlain/react-chips#22]
Even when putting fromsuggestiononly input to false i cannot enter chip without selecting from suggestion box.

**Comment by PelicanMaster** [comment]
After reading the code, [`TAB`](https://github.com/gregchamberlain/react-chips/blob/5b83d8ca28676032107b042dfff0427fe774fea6/src/Chips.js#L226) key is used to [add new chip outside the suggestions](https://github.com/gregchamberlain/react-chips/blob/5b83d8ca28676032107b042dfff0427fe774fea6/src/Chips.js#L43). 

You can customize it using `createChipKeys` property. For example to allow adding chip using `Enter` key or `space` :

    <Chips 
         suggestion={['Harry', 'Ronald', 'Hermione']}
         ...
         createChipKey={[13, ' ']} />

**Comment by gregchamberlain** [comment]
PelicanMaster's comment is the correct answer to this. 👍
