### ISSUE TITLE
Position of suggestions

### ISSUE THREAD

**Issue by CarlosGabrielTovar1991** [gregchamberlain/react-chips#26]
Good day, and congrats for this great package.

The suggestion selector always opens down, if the chips selector is near to bottom of the page or the footer, this is a inconvenient to choose a suggestion far bellow.

How can I modify this behavior?

**Comment by CarlosGabrielTovar1991** [comment]
Hi again!
Maybe the way is to pass some calls trough inputProps, see [Autosugest docs](https://github.com/moroshko/react-autosuggest#inputPropsProp). This way, I can select the correct theme, getting the offset top of the component. But How can I pass inputProps trough Chips props?

**Comment by gregchamberlain** [comment]
Sorry of the delay!

I think the proper way to currently handle this is through the `theme` prop. The Chips theme prop gets passed down to AutoSuggest. Then you can specify a [suggestionsContainer](https://github.com/moroshko/react-autosuggest#theme-optional) styling.

(If you want to extend the default theme you can import it from react-chips/lib/theme and use Object.assign with you theme)

**Comment by CarlosGabrielTovar1991** [comment]
Hi @gregchamberlain 
First, excuse my basic English level, I'll try to write everything correct in this comment.
Second, thank you, effectively I used two themes in a same document, but also I indicate some conditions in the component with uses Chips. Here's an example, maybe can be useful to other users and to you (for a future upgrade with this improvement).

Make sure the component uses ReactDOM to get the Bounding Client Rect of the component. When the component is mounted, add a listener to catch the window scroll and update the top position of the component:

`...
componentDidMount = () => {
	window.addEventListener('scroll', this.getTopInputChips);
}
...`

The React docs recomends to remove the listener in the unmount component:

`...
componentWillUnmount = () => {
	window.removeEventListener('scroll', this.getTopInputChips);
}
...`

Add the function:

`...
getTopInputChips() {
	this.setState({
		offsetTop: ReactDOM.findDOMNode(this).getBoundingClientRect().top + 300,
	});
}
...`

In the constructor, bind the function to the component:

`...
constructor(props) {
	super (props);
	this.getTopInputChips = this.getTopInputChips.bind(this);
	this.state = {};
}
...`

As a plus, can call the function to the onKeyPress event (or even in onClick, onBlur...):

`...
<div className={'MyInputWithChip'} onKeyPress={this.getTopInputChips}>
...`

And in the Chips props, select the theme previously created:

`...
<Chips id={'MyChips'}
...
	theme={this.state.offsetTop > window.innerHeight ? themeTop : themeBottom}
	chipTheme={chipTheme}
/>
...`

In this way, you check where to display the list of suggerences for the Chips.

NOTE: Maybe must insert a default display value (extreme use case).

Greetings from Italy, and again, nice package!
