### ISSUE TITLE
openOnFocus props

### ISSUE THREAD

**Issue by nbob** [gregchamberlain/react-chips#3]
Hello. 
Now `<Autosuggest/>` does not expand if input is focued and value is empty string.

Could you provide a new prop `openOnFocus` on `Chips` component and open `<AutoSuggest>` even if input value is empty?

p.s. Thanks a lot for **react-chips**. Simple to use.

**Comment by gregchamberlain** [comment]
I was going to do some upgrades/maintenance this weekend anyways, so I'll see what I can do!

**Comment by gregchamberlain** [comment]
I just published version 0.4, so if you upgrade to that you can now use shouldRenderSuggestions to accomplish this. Heres an example:

```js
<Chips
  ...
   shouldRenderSuggestions={value => true}
/>
```
